// src/components/Feed/Feed.vue
<script setup lang="ts">
import { computed } from "vue";

import { FeedItem } from "@s:feed/feedItem";
import { filterStore } from "@s:feed/filter";
import { sortStore } from "@s:feed/sort";

import FeedItemComponent from "@c:Feed/FeedItem.vue";
import Filter from "@c:Feed/Filter.vue";
import { MarkdownInstance } from "astro";
import { Frontmatter } from "../../scripts/post";

const emptyItem = {
  dot: "bg-gray-500",
  formattedDate: "Someday...",
  get lang() {
    return document.documentElement.lang;
  },
  title: "There are no posts.",
  url: "",
} as FeedItem;

const { instances } = defineProps<{
  instances: MarkdownInstance<Frontmatter>[];
}>();

const filteredItems = computed(() =>
  instances
    .map((instance) => new FeedItem(instance))
    .filter((item) => filterStore.includes(item.category))
    .sort(sortStore.state.value.function)
);
</script>

<template>
  <Filter />

  <ul id="postFeed" class="text-xl md:text-base">
    <li
      v-for="feedItem in filteredItems"
      :key="feedItem.slug"
      class="border-b border-gray-200 dark:border-gray-700"
    >
      <FeedItemComponent :feedItem="feedItem" />
    </li>

    <li
      v-if="emptyItem && filteredItems.length === 0"
      class="border-b border-gray-200 dark:border-gray-700"
    >
      <FeedItemComponent :feedItem="emptyItem" />
    </li>
  </ul>
</template>

// src/components/Feed/Feed.svelte
<script lang="ts">
  import { sort } from "@scripts/feed/sort";
  import { filter } from "@scripts/feed/filter";
  import { type FeedItem } from "@scripts/feed/feedItem";
  import Filter from "@components/Feed/Filter.svelte";
  import FeedItemComponent from "@components/Feed/FeedItem.svelte";
  import { onMount } from "svelte";

  let emptyItem: FeedItem;

  onMount(() => {
    emptyItem = {
      dot: "bg-gray-500",
      formattedDate: "Someday...",
      lang: document.documentElement.lang,
      title: "There are no posts.",
      url: "",
    } as FeedItem;
  });

  export let feedItems: FeedItem[];
  $: filteredItems = feedItems
    .filter((item) => $filter.includes(item.category))
    .sort($sort.function);
</script>

<Filter />

<ul id="postFeed" class="text-xl md:text-base">
  {#if filteredItems.length}
    {#each filteredItems as feedItem (feedItem.slug)}
      <li class="border-t border-gray-200 dark:border-gray-700">
        <FeedItemComponent {feedItem} />
      </li>{/each}
  {:else}
    <li class="border-t border-gray-200 dark:border-gray-700">
      <FeedItemComponent feedItem={emptyItem} />
    </li>
  {/if}
</ul>
